<a href="https://colab.research.google.com/github/MyDearGreatTeacher/HappyPythonDay/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

偉大的龍大大


## 檢視Google Colab平台的軟體版本

In [0]:
import pandas as pd
print("pandas version: %s" % pd.__version__)

In [0]:
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

# 建立array(陣列)

### 使用np.array()建立陣列

In [0]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

### 使用numpy提供的創建函數直接生成


In [0]:
import numpy as np
x = np.zeros((2, 3))
y=np.arange(2, 3, 0.1) # start, end, step
z=np.linspace(1., 4., 6) # start, end, num
w=np.indices((3, 3))

print(x)
print(y)
print(x)
print(w)

In [0]:
import numpy as np
x = np.zeros((2, 3))
print(x)


In [0]:
import numpy as np

y=np.arange(2, 3, 0.1) # start, end, step

print(y)

In [18]:
import numpy as np

z=np.linspace(1., 4., 6) # start, end, num

print(z)

[1.  1.6 2.2 2.8 3.4 4. ]


### 作業:下列輸出有何不同?

```
np.linspace(2.0, 3.0, num=5)

np.linspace(2.0, 3.0, num=5, endpoint=False)

np.linspace(2.0, 3.0, num=5, retstep=True)
```

參考資料:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html


In [0]:
import numpy as np

#z=np.linspace(1., 4., 6) # start, end, num
#z=np.linspace(2.0, 3.0, num=5, endpoint=False)
z=np.linspace(2.0, 3.0, num=5, retstep=True)

print(z)

###  作業:

```
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])
```

## 屬性:

In [0]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]])

ar2.shape

In [0]:
ar2.ndim

# Ndarray的各種運算 1:Array shape manipulation
```
reshape()
ravel():Flattening a multi-dimensional array


```

### reshape()

In [31]:
x = np.arange(4)
x


array([0, 1, 2, 3])

In [32]:
x.shape

(4,)

In [29]:
x2 = x.reshape(4,1)
x2

array([[0],
       [1],
       [2],
       [3]])

In [33]:
x2.shape

(4, 1)

### 作業:
```
import numpy as np
a=np.array([[0,1],[2,3]])
a.reshape(1,4)
a.reshape(4,1)
```

In [34]:
import numpy as np

a=np.array([[0,1],[2,3]])

print(a)

[[0 1]
 [2 3]]


In [39]:
a.shape

(2, 2)

In [42]:
b = a.reshape(1,4)
b
#b.shape

array([[0, 1, 2, 3]])

In [41]:
c = a.reshape(4,1)
c


array([[0],
       [1],
       [2],
       [3]])

In [0]:
c.shape

### 作業:底下輸出為何?
```
import numpy as np
a=np.arange(2,10).reshape(2,4)
x
```
```
import numpy as np
a=np.arange(2,10).reshape(4,2)
x
```

### 作業:底下輸出為何?
```
import numpy as np

a = np.arange(24).reshape(3,4,2)
b = np.arange(24).reshape(4,3,2)

print(a)
print(b)
```

## Ndarray的各種運算 2:

## Ndarray的各種運算 3:

## Ndarray的各種運算 4:

## Ndarray的各種運算 5:

##  NumPy的效能比較好

比較效能的Built-in magic commands: %timeit

NumPy faster for this than Python



What is %timeit in python?
https://stackoverflow.com/questions/29280470/what-is-timeit-in-python


timeit — Measure execution time of small code snippets
https://docs.python.org/3.7/library/timeit.html

In [43]:
ar=np.arange(1000)
%timeit ar**3

The slowest run took 14.01 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.44 µs per loop


In [44]:
ar=range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 407 µs per loop
